#!/usr/bin/env bash
#
# monitor.sh — one-glance USAGE + capacity report for the deployed stack.
#
# status.sh answers "is it up and who can reach it". This answers "who is using it,
# how hard, is it coping, and what is it costing" — the questions that matter once
# the instance is opened to real users.
#
# Everything here is READ-ONLY (describe/get/list + Logs Insights). It creates no
# resources and changes nothing. Safe to run anytime, paused or live.
#
#   ./monitor.sh            # last 7 days
#   DAYS=1 ./monitor.sh     # last 24h
#   DAYS=30 ./monitor.sh    # last 30 days
#
# Requires deploy/deploy.env (SERVICE, COGNITO_USER_POOL_ID, …) like the other scripts.
set -euo pipefail
cd "$(dirname "$0")"; . ./config.sh

DAYS="${DAYS:-7}"
BUDGET_NAME="${BUDGET_NAME:-kanban-monthly}"
MODEL="${BEDROCK_MODEL_ID}"

# Portable epoch-seconds "N days ago" (BSD date on macOS, GNU date on Linux).
_epoch_days_ago() { date -u -v-"$1"d +%s 2>/dev/null || date -u -d "$1 days ago" +%s; }
START_S="$(_epoch_days_ago "$DAYS")"
END_S="$(date -u +%s)"

# The awslogs group is generated by ECS Express (…-<suffix>), so read it off the
# running container definition rather than guessing the suffix.
log_group() {
  aws ecs describe-task-definition --task-definition "$(effective_task_def)" --region "$REGION" \
    --query "taskDefinition.containerDefinitions[0].logConfiguration.options.\"awslogs-group\"" \
    --output text 2>/dev/null | sed 's/^None$//'
}

# Run a Logs Insights query over the window and print its raw result rows.
# $1 = query string. Blocks until the query completes (or ~40s).
insights() {
  local lg qid status
  lg="$(log_group)"
  [ -n "$lg" ] || { echo "   (no log group resolved — skipping)"; return 0; }
  qid="$(aws logs start-query --log-group-name "$lg" --region "$REGION" \
    --start-time "$START_S" --end-time "$END_S" --query-string "$1" \
    --query 'queryId' --output text 2>/dev/null || true)"
  [ -n "$qid" ] && [ "$qid" != "None" ] || { echo "   (query failed to start)"; return 0; }
  for _ in $(seq 1 20); do
    sleep 2
    status="$(aws logs get-query-results --query-id "$qid" --region "$REGION" \
      --query 'status' --output text 2>/dev/null || echo Failed)"
    [ "$status" = "Complete" ] && break
  done
  aws logs get-query-results --query-id "$qid" --region "$REGION" \
    --query 'results[].[value]' --output text 2>/dev/null
}

echo
say "Columnist usage report — last ${DAYS}d  ($(date -u +%Y-%m-%dT%H:%MZ))"

# ── 1. Service & health ───────────────────────────────────────────────────────
say "Service ($SERVICE)"
aws ecs describe-services --cluster "$CLUSTER" --service "$SERVICE" --region "$REGION" \
  --query 'services[0].{desired:desiredCount,running:runningCount,pending:pendingCount,rollout:deployments[0].rolloutState}' \
  --output table
# Probe the PUBLIC endpoint (CloudFront), not API_HOST: once access-cloudfront.sh has run, the ALB
# security group admits only CloudFront's ranges, so a probe straight at API_HOST from here is
# refused and reads as down when the service is fine. (The ALB does answer on its own *.on.aws
# Host and bare-404s any other Host value — that is the DEPLOY.md 8f AllViewerExceptHostHeader
# trap, and it is why CloudFront must not forward the viewer's Host.)
_health_host="${CLOUDFRONT_DOMAIN:-${API_HOST:-}}"
if [ -n "$_health_host" ]; then
  code="$(curl -s -o /dev/null -w '%{http_code}' "https://$_health_host/api/v1/health" 2>/dev/null)"
  echo "   GET /api/v1/health -> ${code:-unreachable}  (via $_health_host)"
fi

# ── 2. Capacity & autoscaling ─────────────────────────────────────────────────
say "Capacity (autoscaling bounds + CPU target)"
aws application-autoscaling describe-scalable-targets --service-namespace ecs \
  --resource-ids "service/$CLUSTER/$SERVICE" --region "$REGION" \
  --query 'ScalableTargets[0].{min:MinCapacity,max:MaxCapacity}' --output table
aws application-autoscaling describe-scaling-policies --service-namespace ecs \
  --resource-id "service/$CLUSTER/$SERVICE" --region "$REGION" \
  --query 'ScalingPolicies[0].TargetTrackingScalingPolicyConfiguration.{metric:PredefinedMetricSpecification.PredefinedMetricType,target:TargetValue}' \
  --output table

# ── 3. Users (Cognito) ────────────────────────────────────────────────────────
if [ -n "${COGNITO_USER_POOL_ID:-}" ]; then
  say "Users (Cognito $COGNITO_USER_POOL_ID)"
  aws cognito-idp list-users --user-pool-id "$COGNITO_USER_POOL_ID" --region "$REGION" \
    --query 'Users[].{email:Attributes[?Name==`email`]|[0].Value,status:UserStatus,enabled:Enabled}' \
    --output table
  total="$(aws cognito-idp list-users --user-pool-id "$COGNITO_USER_POOL_ID" --region "$REGION" --query 'length(Users)' --output text)"
  pending="$(aws cognito-idp list-users --user-pool-id "$COGNITO_USER_POOL_ID" --region "$REGION" \
    --query 'length(Users[?UserStatus==`FORCE_CHANGE_PASSWORD`])' --output text)"
  echo "   $total accounts · $pending never signed in (still FORCE_CHANGE_PASSWORD)"
else
  warn "COGNITO_USER_POOL_ID unset — skipping user roster"
fi

# ── 4. Activity (from the backend access log) ─────────────────────────────────
say "Logins per day  (POST /auth/login)"
insights 'fields @message
| filter @message like /POST \/api\/v1\/auth\/login/
| stats count(*) as logins by bin(1d) as day
| sort day asc'

say "Agent calls per day  (chat + note-import)"
insights 'fields @message
| filter @message like /agent\/chat/ or @message like /note-imports\/analyze/
| stats count(*) as calls by bin(1d) as day
| sort day asc'

say "Errors per day  (tracebacks / 5xx)"
insights 'fields @message
| filter @message like /Traceback/ or @message like /"HTTP\/1.1" 5/
| stats count(*) as errors by bin(1d) as day
| sort day asc'

# ── 5. Infra peaks ────────────────────────────────────────────────────────────
say "CPU / memory over ${DAYS}d  (peak = 1-min max)"
_start_iso="$(date -u -r "$START_S" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "@$START_S" +%Y-%m-%dT%H:%M:%SZ)"
_end_iso="$(date -u -r "$END_S" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "@$END_S" +%Y-%m-%dT%H:%M:%SZ)"
for m in CPUUtilization MemoryUtilization; do
  printf '   %-18s ' "$m"
  aws cloudwatch get-metric-statistics --namespace AWS/ECS --metric-name "$m" \
    --dimensions Name=ClusterName,Value="$CLUSTER" Name=ServiceName,Value="$SERVICE" \
    --start-time "$_start_iso" --end-time "$_end_iso" \
    --period "$(( DAYS * 86400 + 3600 ))" --statistics Maximum Average --region "$REGION" \
    --query 'Datapoints[0].{peak:Maximum,avg:Average}' --output text 2>/dev/null \
    | awk '{printf "avg %.1f%%  peak %.1f%%\n", $1, $2}' || echo "(no data)"
done

# ── 6. Bedrock tokens ─────────────────────────────────────────────────────────
say "Bedrock tokens over ${DAYS}d  ($MODEL)"
for metric in Invocations InputTokenCount OutputTokenCount CacheReadInputTokenCount CacheWriteInputTokenCount; do
  sum="$(aws cloudwatch get-metric-statistics --namespace AWS/Bedrock --metric-name "$metric" \
    --dimensions Name=ModelId,Value="$MODEL" \
    --start-time "$_start_iso" --end-time "$_end_iso" \
    --period "$(( DAYS * 86400 + 3600 ))" --statistics Sum --region "$REGION" \
    --query 'sum(Datapoints[].Sum)' --output text 2>/dev/null || echo 0)"
  [ "$sum" = "None" ] && sum=0
  printf '   %-28s %s\n' "$metric" "$sum"
done

# ── 7. Budget ─────────────────────────────────────────────────────────────────
say "Budget ($BUDGET_NAME)"
aws budgets describe-budget --account-id "$(account_id)" --budget-name "$BUDGET_NAME" \
  --query 'Budget.{limit:BudgetLimit.Amount,actual:CalculatedSpend.ActualSpend.Amount,forecast:CalculatedSpend.ForecastedSpend.Amount}' \
  --output table 2>/dev/null || echo "   (budget '$BUDGET_NAME' not found — set BUDGET_NAME=)"

echo
